### ISSUE TITLE
我在MAC（M2 cpu），上运行，汉化后遇到的2个错误

### ISSUE THREAD

**Issue by mangitleung** [Hill-98/ptcg-live-zh-mod#2]
你好，我在汉化后遇到的2个错误
1、在我自己会合，点击查看卡片后无法点击关闭。
2、在使用道具丢弃卡后点击完成后画面不消失，卡已经丢弃，完成按钮呈灰色状态无法点击
使用英文原版启动就不会出现这些错误，这些问题能修复吗？

**Comment by Hill-98** [comment]
这些问题均以在最新版本得到解决，你可以前往网盘下载 中文化模组管理器 1.0.1 版本更新解决，

**Comment by mangitleung** [comment]
谢谢告知，我以为GitHub是最新版本
