### ISSUE TITLE
卡沒有變成中文

### ISSUE THREAD

**Issue by RicardoSexy** [Hill-98/ptcg-live-zh-mod#3]
當我裝好之後, 左邊的字都是英文, 沒有變成中文
![image](https://github.com/user-attachments/assets/5769f458-846c-4853-89bd-a0187def501a)

**Comment by Hill-98** [comment]
卡牌左侧文本如果没有对应的翻译文本会显示为原文，强烈建议安装卡牌资源包以获得更完整的中文话。

**Comment by RicardoSexy** [comment]
那想問一下在那可以安装卡牌资源包
而且我檢查了所有卡都是原文, 是不是我安裝方法有問題

**Comment by Hill-98** [comment]
你可以在这里获取预发布版本：https://drive.google.com/drive/folders/1M6ozU3PsHJxV3DWnCeuF3p70VUuaZLDM?usp=sharing

**Comment by RicardoSexy** [comment]
成功了, 多謝
